### ISSUE TITLE
Develop summary table for census tracts by ward

### ISSUE THREAD

**Issue by geneorama** [Chicago/census2020_ward_rpt#1]
Develop a table in Markdown / R Markdown

Draft of table contents 

| Tract       | TotPop | TotHH | LEPspanHHs | HH_Renter_Crowded | Owner_TOTAL | Renter_TOTAL | Pct Renter | NoInternet | IntFirstEng |
|-------------|--------|-------|------------|-------------------|-------------|--------------|------------|------------|-------------|
| 17031010501 | 4,147  | 2,425 | 0          | 30                | 291         | 2,134        | 88%        | 526        | 2,652       |
| 17031010502 | 2,802  | 1,508 | 29         | 70                | 287         | 1,221        | 81%        | 262        | 1,796       |
| 17031010503 | 1,713  | 968   | 20         | 59                | 197         | 771          | 80%        | 308        | 1,258       |

I used this site to create the table above from something in Excel: https://www.tablesgenerator.com/markdown_tables  The ratio column is calculated in Excel.

@DForbush can you put something like that in ./app/dev.R?

**Comment by geneorama** [comment]
One thing we talked about using is reactable
https://glin.github.io/reactable/

The other thing we talked about was DT
https://rstudio.github.io/DT/

I'll try to get you an example of DT

**Comment by DForbush** [comment]
I've started a draft data table in the R Markdown file, CensusWardReport.Rmd, lines 54-62. It needs a lot of re-formatting but it's a start. I also recognize that there's probably a way to make this table easier to edit and refine. 

Does this need to be in dev.R?

**Comment by geneorama** [comment]
No. Just thought it would be a good starting point because it pulls in the global data.

An .Rmd file’s better

**Comment by geneorama** [comment]
We have a draft, closing the issue.  Great job @DForbush
