### ISSUE TITLE
plan for cic.ward_daily_rates_2020

### ISSUE THREAD

**Issue by geneorama** [Chicago/census2020_ward_rpt#10]
What is the plan for this table?

I know this is dummy data (should be zeros), but I don't understand why there are 25 rows for each ward / day. For example, ward 1  has 25 entries for 2020-03-12. 

Also, there is an NA ward.

**Comment by srao-civis** [comment]
This table should have only one entry per ward now (and no NA ward)! Sorry about that. It was an artifact from generating the table from the 2010 data and forcing there to be only one date and rate. 

Goal is to update the table daily through platform with the actual daily response rates and keep the same table format.

**Comment by geneorama** [comment]
Ok, that makes sense, thank you
