### ISSUE TITLE
Matching tract numbers between CIC and other census data

### ISSUE THREAD

**Issue by geneorama** [Chicago/census2020_ward_rpt#6]
I was trying to understand the CIC numbers, such as Census Hard to Count, and what that percentage means. 

I happened to pick Tract 20702 Block 3 as an example.

I tried to match it to a tract in the planning database file `data_census_planning\pdb2017tract_2010MRR_2018ACS_IL.xlsx`. I could not find an exact match. Two tracts contained "20702"; 17031020702 and 17031220702, but the population doesn't match for either. 

![image](https://user-images.githubusercontent.com/1392068/75577934-9698a800-5a28-11ea-9079-1a6b69bce930.png)

@DForbush did you ever resolve this matching issue?

**Comment by DForbush** [comment]
I did not really resolve the matching issue. I simply started using the data from the Civis API, following the instructions located [here]( https://civisanalytics.github.io/civis-r/).

That's concerning that you can't find a match. Just to confirm, however, are you sure you're looking at the block data? I think that excel file is the tract-level data, and you're comparing it with block data that's loaded into the CIC.

**Comment by geneorama** [comment]
Can you see the screen shot in the original issue? The CIC label is "Tract 20702".  It's by Peterson and Francisco, I'll check in another map.

**Comment by DForbush** [comment]
Yes, the screenshot is only showing Block 3 of Tract 20702, where as that Excel sheet is at the tract level and would include multiple blocks.

**Comment by geneorama** [comment]
Here's a link to the statistics in the HTC map: https://www.censushardtocountmaps2020.us/?latlng=41.99491%2C-87.69894&z=16&query=coordinates%3A%3A41.99273%2C-87.70223&promotedfeaturetype=censusTracts&arp=arpRaceEthnicity&baselayerstate=0&infotab=info-contact&filterQuery=false

Tract 207.02 in Cook County, IL
Based on the latest census estimates (for 2014-2018), 7,473 people live in 2,343 households in this tract, and 201 people live in group quarters. (Total population = 7,674.)

**Comment by geneorama** [comment]
@DForbush My last reply was a little hasty, I hadn't seen your response yet.

So, this makes a bit more sense. In the CIC blocks 1,2,3, and 4, have populations of 2626, 2574, 2043, and 600.  This adds up to 7843, which roughly matches the HTC map. 

In the Census / HTC data the FIP code for the tract is 207.02.  The other tract I found is 2207.02.  Of course it's hard to tell that the match is spurious when looking at the longer number.

**Comment by geneorama** [comment]
At this point I think I can match the tracts between the CIC and the Census Planning Database, but I have questions about the fields.  So, closing this issue and opening one about the fields.
