### ISSUE TITLE
Source of CIC data / meaning of HTC values

### ISSUE THREAD

**Issue by geneorama** [Chicago/census2020_ward_rpt#7]
I was trying to understand the source for the Census Hard to Count percentages in the CIC. On the HTC maps and the Census Bureau sites I've only seen _scores_, so I was wondering about the source for HTC _population percentages_.

I started with the example #6, tract 207.02, I had a hard time reconciling the figures from the CIC to the planning database.  Am I missing something?

I took these 4 blocks in the tract:
![image](https://user-images.githubusercontent.com/1392068/75816641-302ec500-5d5b-11ea-8858-01e35b043bd7.png)

I then compiled those into a small table. The total column is based on the sum product of the percentages and the populations:
![image](https://user-images.githubusercontent.com/1392068/75816669-3cb31d80-5d5b-11ea-9c26-5b48a81da11a.png)

The CIC number looks similar to the Total Population from the planning database, but I'm not seeing good matches on the rest of the numbers:

![image](https://user-images.githubusercontent.com/1392068/75816874-9b789700-5d5b-11ea-8b50-9eac7c47f40f.png)

The full example can be found in the attached excel file.

[Civis example 20702.xlsx](https://github.com/Chicago/census2020_ward_rpt/files/4283451/Civis.example.20702.xlsx)

**Comment by sherryshenker** [comment]
Hi Gene, the Census HTC values correspond to the "low_response_score" column in the Census' 2020 block-group level Planning Database. You're right, these are technically scores, not percentages.

 If you run the following query in Civis Platform on the planning database, you should see numbers that match up to the tooltip in the map. Let me know if you're still having issues!

<img width="593" alt="Screen Shot 2020-03-03 at 3 36 00 PM" src="https://user-images.githubusercontent.com/15897802/75821924-b13e8a00-5d64-11ea-9f1e-201cc864e210.png">

**Comment by geneorama** [comment]
@sherryshenker Thank you, I didn't know about the block level database, I had only seen the tract leveI. 

I think there might be an issue with non English speakers.  I used LEP (Limited English Proficiency) from the tract data, not sure what the CIC is using, but our percentages are very different.

It's interesting how the block / tract data differs, most of the differences are probably explained by that.

**Comment by sherryshenker** [comment]
For non-English speaking, I used "pct_othr_lang_acs_13_17" from the block group data dictionary. The table I shared, `cic.data_dict` in Platform, has all of the column mappings.  We try to use blockgroup data when possible to make things granular, and make a note when Tract-level data is used instead. (hence the "(tract)" call outs)

**Comment by geneorama** [comment]
@sherryshenker is the write up for the CIC score public?

**Comment by geneorama** [comment]
@sherryshenker spoke with you on the phone, and I won't put the write up in the repo.  It would be good to link to it later when it's on the civis site.  Thanks!
