### ISSUE TITLE
Technical question about Civis Platform - read vs query

### ISSUE THREAD

**Issue by geneorama** [Chicago/census2020_ward_rpt#9]
@sherryshenker (or others) what's the difference between these?

```R
civis::read_civis("cic.ward_visualization_table", database="City of Chicago")
civis::query_civis("SELECT * FROM cic.ward_visualization_table;", database="City of Chicago")
```

For the bigger tables I was hoping to select just the columns we need, but I'm not getting the same results when I execute a query vs `read_civis`.  Is there a way to filter columns with the `read_civis` function?

**Comment by sherryshenker** [comment]
`query_civis` executes a query without returning a result. I think you can use `read_civis` with a SQL query to do what you want. e.g. `df <- civis::read_civis(sql("select ward, civis_2020_target from cic.ward_visualization_table"), database="City of Chicago")` let me know if that works!

**Comment by geneorama** [comment]
Looks good, thanks
